{{- if .Values.deploy.enabled }}
{{- include "wildfly-common.deploymentconfig" (list . "wildfly.deploymentconfig") -}}
{{- end -}}

{{ define "wildfly.deploymentconfig" }}
{{- include "wildfly.metadata.labels" . }}
spec:
  template:
    {{- include "wildfly.metadata.labels" . | nindent 4 }}
{{- end -}}