{{- if and .Values.build.enabled -}}
{{- if(eq .Values.build.mode "s2i") -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "wildfly.appBuilderImage" . }}
  labels:
{{- include "wildfly.labels" . | nindent 4 }}
---
{{- end -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "wildfly.appName" . }}
  labels:
{{- include "wildfly.labels" . | nindent 4 }}
{{- end -}}