{{- if .Values.build.enabled -}}
{{- include "wildfly-common.imagestream" (list . "wildfly.imagestream") -}}
{{- end -}}

{{- define "wildfly.imagestream" -}}
{{- include "wilfly.metadata.labels" . }}
  name: {{ include "wildfly-common.appImage" . }}
{{- end -}}
