{{- if .Values.build.enabled -}}
{{- include "wildfly-common.imagestream" (list . "wildfly.imagestream") -}}
{{- end -}}

{{- define "wildfly.imagestream" -}}
metadata:
  name: {{ include "wildfly-common.appImage" . }}
  labels:
    {{- include "wildfly.labels" . | nindent 4 }}
{{- end -}}
