# Deploy a Todo Backend
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:keywords:          openshift,eap,helm

This example shows how to deploy a https://todobackend.com[ToDo backend] on OpenShift that uses WildFly as the backend and PostgreSQL as the database.

## Prerequisites

### Deploy a PostgreSQL DB on OpenShift

Using the "PostgreSQL (Ephemeral)" template to create a database service named `todos-db`
that provides a database named `todos`:

[source,options="nowrap"]
----
$ oc new-app postgresql-ephemeral \
   -p DATABASE_SERVICE_NAME=todos-db \
   -p POSTGRESQL_DATABASE=todos
----

You don't need to note the credentials to connect to this database as we will use the 
`secret` created by the template to get them from the backend.

## Source Code

The source code for the backend is hosted at https://github.com/jmesnil/quickstart/tree/todo-backend/todo-backend.

It is a simple Java EE application that uses JPA to connect to a PostgreSQL server and exposes its REST API using JAX-RS.

When the backend is deployed on OpenShift, it needs some environment variables to connect to the PostgreSQL database. They are all specified in the `deploy.env` section of the Helm Chart as well as environment variables to support CORS filter (required by the Web application that will connect to the ToDo backend using JavaScript calls).

## Installation

[source,options="nowrap"]
----
$ helm install todo-backend -f examples/todo-backend/todo-backend.yaml ./charts/wildfly
----

Let's wait for the application to be built and deployed:

[source,options="nowrap"]
----
$ oc get dc/todo-backend -w
NAME           REVISION   DESIRED   CURRENT   TRIGGERED BY
todo-backend   0          3         0         config,image(todo-backend:latest)
...
todo-backend   1          3         3         config,image(todo-backend:latest)
----

## Use the ToDo application

Once the backend is deployed on OpenShift, it can be accessed from the route `todo-backend`.
Let's find the host that we can use to connect to this backend:

[source,options="nowrap"]
----
$ oc get route todo-backend -o jsonpath="{.spec.host}"
todo-backend-jmesnil1-code.apps.sandbox.x8i5.p1.openshiftapps.com
----

This value will be different for every installation of the Backend.

[NOTE]
====
Make sure to prepend the host with `https://` to be able to connect to the backend from the ToDo Backend Specs or Client
====

We can verify that this application is properly working as a ToDo Backend by running its https://todobackend.com/specs/index.html[specs] on it.


Once all tests passed, we can use the https://todobackend.com/client/index.html[ToDo Backend client] to have a Web application connected to the backend.

## Clean up

The backend can be deleted by running the command:

[source,options="nowrap"]
----
$ helm delete todo-backend
release "todo-backend" uninstalled
----

The database can be deleted by running the command:

[source,options="nowrap"]
----
$ oc delete all -l template=postgresql-ephemeral-template
----
