image:
  ## Name of the image you want to build/deploy
  ## Defaults to the release name
  name:
    ## Tag that you want to build/deploy
  tag: latest
build:
  enabled: true
  mode: bootable-jar
  bootableJar:
    builderImage: registry.access.redhat.com/ubi8/openjdk-11:latest
  s2i:
    builderImage: quay.io/wildfly/wildfly-centos7
    runtimeImage: quay.io/wildfly/wildfly-runtime-centos7
deploy:
  enabled: true
  route:
    enabled: true
  livenessProbe:
    httpGet:
        path: /health/live
        port: admin
  readinessProbe:
    httpGet:
        path: /health/ready
        port: admin