# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

build:
  enabled: true
  mode: bootable-jar
  bootableJar:
    artifactDir: target
deploy:
  route:
    enabled: true
  livenessProbe:
    httpGet:
        path: /health/live
        port: admin
  readinessProbe:
    httpGet:
        path: /health/ready
        port: admin