build:
  mode: bootable-jar
  uri: https://github.com/wildfly/quickstart.git
  ref: 22.0.1.Final
  bootableJar:
    artifactDir: microprofile-config/target
  env:
  - name: MAVEN_ARGS_APPEND
    value: -am -pl microprofile-config -P bootable-jar-openshift -Djkube.skip=true
  - name: MAVEN_OPTS
    value: '-XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m'
deploy:
  replicas: 1
  env:
  - name: CONFIG_PROP
    value: Hello from OpenShift