{{- define "wildfly-common.buildconfig-s2i.tpl" -}}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "wildfly-common.appName" . }}
  labels: {}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "wildfly-common.appImageStreamTag" . }}
  source:
    type: Docker
    images:
    - from:
        kind: ImageStreamTag
        name: {{ include "wildfly-common.appBuilderImage" . }}:latest
      paths:
      - destinationDir: .
        sourcePath: /s2i-output/server/
  strategy:
    dockerStrategy:
      from: {}
    type: Docker
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: {{ include "wildfly-common.appBuilderImage" . }}:latest
    type: ImageChange
  - type: ConfigChange
{{ end }}

{{- define "wildfly-common.buildconfig-s2i" -}}
{{- include "wildfly-common.util.merge" (append . "wildfly-common.buildconfig-s2i.tpl") -}}
{{- end -}}