{{- define "wildfly-common.buildconfig-bootable-jar.tpl" -}}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "wildfly-common.appName" . }}
  labels: {}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "wildfly-common.appImageStreamTag" . }}
  source:
    type: Git
    git:
      ref: {{ .Values.build.ref }}
      uri: {{ required "Git source repository URL is required" .Values.build.uri }}
    {{- if .Values.build.contextDir }}
    contextDir: {{ .Values.build.contextDir }}
    {{- end }}
    {{- if .Values.build.images }}
    images:
      {{- tpl (toYaml .Values.build.images) . | nindent 6 }}
    {{- end}}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ quote .Values.build.bootableJar.builderImage }}
      {{- if .Values.build.env }}
      env:
        {{- tpl (toYaml .Values.build.env) . | nindent 8 }}
      {{- end }}
      incremental: true
      forcePull: true
{{- if .Values.build.resources }}
  resources:
    {{- toYaml .Values.build.resources | nindent 4 }}
{{- end }}
  triggers:
  - type: ConfigChange
  runPolicy: Serial
{{- end }}

{{- define "wildfly-common.buildconfig-bootable-jar" -}}
{{- include "wildfly-common.util.merge" (append . "wildfly-common.buildconfig-bootable-jar.tpl") -}}
{{- end -}}