{{- define "wildfly-common.route" -}}
{{- if (and .Values.deploy.enabled .Values.deploy.route.enabled) }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "wildfly.appName" . }}
  labels:
  {{- include "wildfly.labels" . | nindent 4 }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: {{ include "wildfly.appName" . }}
    weight: 100
  {{- if .Values.deploy.route.tls.enabled }}
  tls:
    termination: {{ .Values.deploy.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.deploy.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
{{- end }}
